version: "3.9"
services: 
  mqtt-simulator:
    depends_on:
      - broker
    build:
      context: ./mqtt-simulator
      args: 
        tag: "mqtt-sim"
  subscriber:
    environment:
      -  INFLUX_TOKEN=F8FeBt5rxbrDDNnu0IIZuKMnSArNPGI6FI75kjaMIapA1N21eLUYYpWq4R3xz4h2jnVinZxX1XFLw_O3FO_s_w==
    depends_on:
      - broker
    build:
      context: ./subscriber
      args: 
        tag: "subscriber"
  broker:
    image: "eclipse-mosquitto:2.0.12"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"

  



  
