apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mohsin
  labels:
    team: il-tempo-gigante
    service: itg
spec:
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: wss
      port: 9001
      targetPort: 9001
  selector:
    app: mosquitto
  type: LoadBalancer
  externalTrafficPolicy: Local